[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar /app/app.jar"
healthcheckPath = "/api/product/list"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SPRING_DATASOURCE_URL = "jdbc:postgresql://${RAILWAY_PRIVATE_DOMAIN}:5432/${PGDATABASE}"
SPRING_DATASOURCE_USERNAME = "${PGUSER}"
SPRING_DATASOURCE_PASSWORD = "${PGPASSWORD}"
SPRING_JPA_HIBERNATE_DDL_AUTO = "update"
PORT = "8080" 